import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
test('Postgres: private data, history, concurrency and server validation',async()=>{
  const db=new PGlite();
  await db.exec(`create role anon;create role authenticated;create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema public,auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
    insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');`);
  await db.exec(await readFile(new URL('../supabase/001_nexo.sql',import.meta.url),'utf8'));
  const asUser=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
  const state={accounts:[{id:'a1',person:'juan',name:'Banco',type:'Efectivo',initialBalance:1000000}],budgets:[],goals:[],movements:[]};
  const save=revision=>db.query('select public.save_nexo($1::jsonb,$2) as data',[JSON.stringify(state),revision]);
  await asUser('11111111-1111-4111-8111-111111111111');
  assert.equal((await save(0)).rows[0].data.revision,1);
  assert.equal((await db.query('select * from public.nexo_history')).rows.length,1);
  state.movements=[{id:'m1',type:'expense',person:'juan',accountId:'a1',amount:100000,date:'2026-09-06',concept:'Mercado',note:'',goalId:'',budgetId:''}];
  assert.equal((await save(1)).rows[0].data.revision,2);
  await assert.rejects(save(1),/otra pestaña/);
  assert.equal((await db.query('select * from public.nexo_history')).rows.length,2);
  state.movements[0].amount=2000000;await assert.rejects(save(2),/saldo suficiente/);
  assert.equal((await db.query('select revision from public.nexo_ledgers')).rows[0].revision,2);
  await assert.rejects(db.exec('delete from public.nexo_history'),/permission denied/);
  await asUser('22222222-2222-4222-8222-222222222222');
  assert.equal((await db.query('select * from public.nexo_ledgers')).rows.length,0);
  assert.equal((await db.query('select * from public.nexo_history')).rows.length,0);
  state.movements=[];assert.equal((await save(0)).rows[0].data.revision,1);
  assert.equal((await db.query('select * from public.nexo_ledgers')).rows.length,1);
  await assert.rejects(db.query('insert into public.nexo_ledgers(user_id,payload) values($1,$2)', ['11111111-1111-4111-8111-111111111111',JSON.stringify(state)]),/Acceso no permitido|row-level security/);
  await db.exec("reset role;select set_config('request.jwt.claim.sub','',false);set role anon;");
  await assert.rejects(db.exec('select * from public.nexo_ledgers'),/permission denied/);
  await assert.rejects(save(0),/permission denied/);
  await db.close();
});
